package OEMRA;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResWithCert.proto

public final class ResWithCert {
  private ResWithCert() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResWithCertFormatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResWithCertFormat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .CertInfo certInfo = 1;</code>
     */
    java.util.List<ResWithCert.CertInfo> 
        getCertInfoList();
    /**
     * <code>repeated .CertInfo certInfo = 1;</code>
     */
    ResWithCert.CertInfo getCertInfo(int index);
    /**
     * <code>repeated .CertInfo certInfo = 1;</code>
     */
    int getCertInfoCount();
    /**
     * <code>repeated .CertInfo certInfo = 1;</code>
     */
    java.util.List<? extends ResWithCert.CertInfoOrBuilder> 
        getCertInfoOrBuilderList();
    /**
     * <code>repeated .CertInfo certInfo = 1;</code>
     */
    ResWithCert.CertInfoOrBuilder getCertInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ResWithCertFormat}
   */
  public  static final class ResWithCertFormat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResWithCertFormat)
      ResWithCertFormatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResWithCertFormat.newBuilder() to construct.
    private ResWithCertFormat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResWithCertFormat() {
      certInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResWithCertFormat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                certInfo_ = new java.util.ArrayList<ResWithCert.CertInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              certInfo_.add(
                  input.readMessage(ResWithCert.CertInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          certInfo_ = java.util.Collections.unmodifiableList(certInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ResWithCert.internal_static_ResWithCertFormat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ResWithCert.internal_static_ResWithCertFormat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResWithCert.ResWithCertFormat.class, ResWithCert.ResWithCertFormat.Builder.class);
    }

    public static final int CERTINFO_FIELD_NUMBER = 1;
    private java.util.List<ResWithCert.CertInfo> certInfo_;
    /**
     * <code>repeated .CertInfo certInfo = 1;</code>
     */
    public java.util.List<ResWithCert.CertInfo> getCertInfoList() {
      return certInfo_;
    }
    /**
     * <code>repeated .CertInfo certInfo = 1;</code>
     */
    public java.util.List<? extends ResWithCert.CertInfoOrBuilder> 
        getCertInfoOrBuilderList() {
      return certInfo_;
    }
    /**
     * <code>repeated .CertInfo certInfo = 1;</code>
     */
    public int getCertInfoCount() {
      return certInfo_.size();
    }
    /**
     * <code>repeated .CertInfo certInfo = 1;</code>
     */
    public ResWithCert.CertInfo getCertInfo(int index) {
      return certInfo_.get(index);
    }
    /**
     * <code>repeated .CertInfo certInfo = 1;</code>
     */
    public ResWithCert.CertInfoOrBuilder getCertInfoOrBuilder(
        int index) {
      return certInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getCertInfoCount(); i++) {
        if (!getCertInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < certInfo_.size(); i++) {
        output.writeMessage(1, certInfo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < certInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, certInfo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ResWithCert.ResWithCertFormat)) {
        return super.equals(obj);
      }
      ResWithCert.ResWithCertFormat other = (ResWithCert.ResWithCertFormat) obj;

      boolean result = true;
      result = result && getCertInfoList()
          .equals(other.getCertInfoList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCertInfoCount() > 0) {
        hash = (37 * hash) + CERTINFO_FIELD_NUMBER;
        hash = (53 * hash) + getCertInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ResWithCert.ResWithCertFormat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResWithCert.ResWithCertFormat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResWithCert.ResWithCertFormat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResWithCert.ResWithCertFormat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResWithCert.ResWithCertFormat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResWithCert.ResWithCertFormat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResWithCert.ResWithCertFormat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResWithCert.ResWithCertFormat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResWithCert.ResWithCertFormat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ResWithCert.ResWithCertFormat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResWithCert.ResWithCertFormat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResWithCert.ResWithCertFormat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ResWithCert.ResWithCertFormat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResWithCertFormat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResWithCertFormat)
        ResWithCert.ResWithCertFormatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ResWithCert.internal_static_ResWithCertFormat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ResWithCert.internal_static_ResWithCertFormat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResWithCert.ResWithCertFormat.class, ResWithCert.ResWithCertFormat.Builder.class);
      }

      // Construct using ResWithCert.ResWithCertFormat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCertInfoFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (certInfoBuilder_ == null) {
          certInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          certInfoBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ResWithCert.internal_static_ResWithCertFormat_descriptor;
      }

      public ResWithCert.ResWithCertFormat getDefaultInstanceForType() {
        return ResWithCert.ResWithCertFormat.getDefaultInstance();
      }

      public ResWithCert.ResWithCertFormat build() {
        ResWithCert.ResWithCertFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ResWithCert.ResWithCertFormat buildPartial() {
        ResWithCert.ResWithCertFormat result = new ResWithCert.ResWithCertFormat(this);
        int from_bitField0_ = bitField0_;
        if (certInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            certInfo_ = java.util.Collections.unmodifiableList(certInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.certInfo_ = certInfo_;
        } else {
          result.certInfo_ = certInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResWithCert.ResWithCertFormat) {
          return mergeFrom((ResWithCert.ResWithCertFormat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResWithCert.ResWithCertFormat other) {
        if (other == ResWithCert.ResWithCertFormat.getDefaultInstance()) return this;
        if (certInfoBuilder_ == null) {
          if (!other.certInfo_.isEmpty()) {
            if (certInfo_.isEmpty()) {
              certInfo_ = other.certInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCertInfoIsMutable();
              certInfo_.addAll(other.certInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.certInfo_.isEmpty()) {
            if (certInfoBuilder_.isEmpty()) {
              certInfoBuilder_.dispose();
              certInfoBuilder_ = null;
              certInfo_ = other.certInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              certInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCertInfoFieldBuilder() : null;
            } else {
              certInfoBuilder_.addAllMessages(other.certInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getCertInfoCount(); i++) {
          if (!getCertInfo(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResWithCert.ResWithCertFormat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResWithCert.ResWithCertFormat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ResWithCert.CertInfo> certInfo_ =
        java.util.Collections.emptyList();
      private void ensureCertInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          certInfo_ = new java.util.ArrayList<ResWithCert.CertInfo>(certInfo_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ResWithCert.CertInfo, ResWithCert.CertInfo.Builder, ResWithCert.CertInfoOrBuilder> certInfoBuilder_;

      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public java.util.List<ResWithCert.CertInfo> getCertInfoList() {
        if (certInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(certInfo_);
        } else {
          return certInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public int getCertInfoCount() {
        if (certInfoBuilder_ == null) {
          return certInfo_.size();
        } else {
          return certInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public ResWithCert.CertInfo getCertInfo(int index) {
        if (certInfoBuilder_ == null) {
          return certInfo_.get(index);
        } else {
          return certInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public Builder setCertInfo(
          int index, ResWithCert.CertInfo value) {
        if (certInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCertInfoIsMutable();
          certInfo_.set(index, value);
          onChanged();
        } else {
          certInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public Builder setCertInfo(
          int index, ResWithCert.CertInfo.Builder builderForValue) {
        if (certInfoBuilder_ == null) {
          ensureCertInfoIsMutable();
          certInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          certInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public Builder addCertInfo(ResWithCert.CertInfo value) {
        if (certInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCertInfoIsMutable();
          certInfo_.add(value);
          onChanged();
        } else {
          certInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public Builder addCertInfo(
          int index, ResWithCert.CertInfo value) {
        if (certInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCertInfoIsMutable();
          certInfo_.add(index, value);
          onChanged();
        } else {
          certInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public Builder addCertInfo(
          ResWithCert.CertInfo.Builder builderForValue) {
        if (certInfoBuilder_ == null) {
          ensureCertInfoIsMutable();
          certInfo_.add(builderForValue.build());
          onChanged();
        } else {
          certInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public Builder addCertInfo(
          int index, ResWithCert.CertInfo.Builder builderForValue) {
        if (certInfoBuilder_ == null) {
          ensureCertInfoIsMutable();
          certInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          certInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public Builder addAllCertInfo(
          java.lang.Iterable<? extends ResWithCert.CertInfo> values) {
        if (certInfoBuilder_ == null) {
          ensureCertInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, certInfo_);
          onChanged();
        } else {
          certInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public Builder clearCertInfo() {
        if (certInfoBuilder_ == null) {
          certInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          certInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public Builder removeCertInfo(int index) {
        if (certInfoBuilder_ == null) {
          ensureCertInfoIsMutable();
          certInfo_.remove(index);
          onChanged();
        } else {
          certInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public ResWithCert.CertInfo.Builder getCertInfoBuilder(
          int index) {
        return getCertInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public ResWithCert.CertInfoOrBuilder getCertInfoOrBuilder(
          int index) {
        if (certInfoBuilder_ == null) {
          return certInfo_.get(index);  } else {
          return certInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public java.util.List<? extends ResWithCert.CertInfoOrBuilder> 
           getCertInfoOrBuilderList() {
        if (certInfoBuilder_ != null) {
          return certInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(certInfo_);
        }
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public ResWithCert.CertInfo.Builder addCertInfoBuilder() {
        return getCertInfoFieldBuilder().addBuilder(
            ResWithCert.CertInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public ResWithCert.CertInfo.Builder addCertInfoBuilder(
          int index) {
        return getCertInfoFieldBuilder().addBuilder(
            index, ResWithCert.CertInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .CertInfo certInfo = 1;</code>
       */
      public java.util.List<ResWithCert.CertInfo.Builder> 
           getCertInfoBuilderList() {
        return getCertInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ResWithCert.CertInfo, ResWithCert.CertInfo.Builder, ResWithCert.CertInfoOrBuilder> 
          getCertInfoFieldBuilder() {
        if (certInfoBuilder_ == null) {
          certInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ResWithCert.CertInfo, ResWithCert.CertInfo.Builder, ResWithCert.CertInfoOrBuilder>(
                  certInfo_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          certInfo_ = null;
        }
        return certInfoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResWithCertFormat)
    }

    // @@protoc_insertion_point(class_scope:ResWithCertFormat)
    private static final ResWithCert.ResWithCertFormat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResWithCert.ResWithCertFormat();
    }

    public static ResWithCert.ResWithCertFormat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ResWithCertFormat>
        PARSER = new com.google.protobuf.AbstractParser<ResWithCertFormat>() {
      public ResWithCertFormat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResWithCertFormat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResWithCertFormat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResWithCertFormat> getParserForType() {
      return PARSER;
    }

    public ResWithCert.ResWithCertFormat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CertInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CertInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes certFile = 1;</code>
     */
    boolean hasCertFile();
    /**
     * <code>required bytes certFile = 1;</code>
     */
    com.google.protobuf.ByteString getCertFile();

    /**
     * <code>required string certFileName = 2;</code>
     */
    boolean hasCertFileName();
    /**
     * <code>required string certFileName = 2;</code>
     */
    java.lang.String getCertFileName();
    /**
     * <code>required string certFileName = 2;</code>
     */
    com.google.protobuf.ByteString
        getCertFileNameBytes();
  }
  /**
   * Protobuf type {@code CertInfo}
   */
  public  static final class CertInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CertInfo)
      CertInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CertInfo.newBuilder() to construct.
    private CertInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CertInfo() {
      certFile_ = com.google.protobuf.ByteString.EMPTY;
      certFileName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CertInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              certFile_ = input.readBytes();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              certFileName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ResWithCert.internal_static_CertInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ResWithCert.internal_static_CertInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResWithCert.CertInfo.class, ResWithCert.CertInfo.Builder.class);
    }

    private int bitField0_;
    public static final int CERTFILE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString certFile_;
    /**
     * <code>required bytes certFile = 1;</code>
     */
    public boolean hasCertFile() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes certFile = 1;</code>
     */
    public com.google.protobuf.ByteString getCertFile() {
      return certFile_;
    }

    public static final int CERTFILENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object certFileName_;
    /**
     * <code>required string certFileName = 2;</code>
     */
    public boolean hasCertFileName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string certFileName = 2;</code>
     */
    public java.lang.String getCertFileName() {
      java.lang.Object ref = certFileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          certFileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string certFileName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCertFileNameBytes() {
      java.lang.Object ref = certFileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        certFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCertFile()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCertFileName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, certFile_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, certFileName_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, certFile_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, certFileName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ResWithCert.CertInfo)) {
        return super.equals(obj);
      }
      ResWithCert.CertInfo other = (ResWithCert.CertInfo) obj;

      boolean result = true;
      result = result && (hasCertFile() == other.hasCertFile());
      if (hasCertFile()) {
        result = result && getCertFile()
            .equals(other.getCertFile());
      }
      result = result && (hasCertFileName() == other.hasCertFileName());
      if (hasCertFileName()) {
        result = result && getCertFileName()
            .equals(other.getCertFileName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCertFile()) {
        hash = (37 * hash) + CERTFILE_FIELD_NUMBER;
        hash = (53 * hash) + getCertFile().hashCode();
      }
      if (hasCertFileName()) {
        hash = (37 * hash) + CERTFILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getCertFileName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ResWithCert.CertInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResWithCert.CertInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResWithCert.CertInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResWithCert.CertInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResWithCert.CertInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResWithCert.CertInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResWithCert.CertInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResWithCert.CertInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResWithCert.CertInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ResWithCert.CertInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResWithCert.CertInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResWithCert.CertInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ResWithCert.CertInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CertInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CertInfo)
        ResWithCert.CertInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ResWithCert.internal_static_CertInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ResWithCert.internal_static_CertInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResWithCert.CertInfo.class, ResWithCert.CertInfo.Builder.class);
      }

      // Construct using ResWithCert.CertInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        certFile_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        certFileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ResWithCert.internal_static_CertInfo_descriptor;
      }

      public ResWithCert.CertInfo getDefaultInstanceForType() {
        return ResWithCert.CertInfo.getDefaultInstance();
      }

      public ResWithCert.CertInfo build() {
        ResWithCert.CertInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ResWithCert.CertInfo buildPartial() {
        ResWithCert.CertInfo result = new ResWithCert.CertInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.certFile_ = certFile_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.certFileName_ = certFileName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResWithCert.CertInfo) {
          return mergeFrom((ResWithCert.CertInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResWithCert.CertInfo other) {
        if (other == ResWithCert.CertInfo.getDefaultInstance()) return this;
        if (other.hasCertFile()) {
          setCertFile(other.getCertFile());
        }
        if (other.hasCertFileName()) {
          bitField0_ |= 0x00000002;
          certFileName_ = other.certFileName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCertFile()) {
          return false;
        }
        if (!hasCertFileName()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResWithCert.CertInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResWithCert.CertInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString certFile_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes certFile = 1;</code>
       */
      public boolean hasCertFile() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes certFile = 1;</code>
       */
      public com.google.protobuf.ByteString getCertFile() {
        return certFile_;
      }
      /**
       * <code>required bytes certFile = 1;</code>
       */
      public Builder setCertFile(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        certFile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes certFile = 1;</code>
       */
      public Builder clearCertFile() {
        bitField0_ = (bitField0_ & ~0x00000001);
        certFile_ = getDefaultInstance().getCertFile();
        onChanged();
        return this;
      }

      private java.lang.Object certFileName_ = "";
      /**
       * <code>required string certFileName = 2;</code>
       */
      public boolean hasCertFileName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string certFileName = 2;</code>
       */
      public java.lang.String getCertFileName() {
        java.lang.Object ref = certFileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            certFileName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string certFileName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCertFileNameBytes() {
        java.lang.Object ref = certFileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          certFileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string certFileName = 2;</code>
       */
      public Builder setCertFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        certFileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string certFileName = 2;</code>
       */
      public Builder clearCertFileName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        certFileName_ = getDefaultInstance().getCertFileName();
        onChanged();
        return this;
      }
      /**
       * <code>required string certFileName = 2;</code>
       */
      public Builder setCertFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        certFileName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CertInfo)
    }

    // @@protoc_insertion_point(class_scope:CertInfo)
    private static final ResWithCert.CertInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResWithCert.CertInfo();
    }

    public static ResWithCert.CertInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CertInfo>
        PARSER = new com.google.protobuf.AbstractParser<CertInfo>() {
      public CertInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CertInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CertInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CertInfo> getParserForType() {
      return PARSER;
    }

    public ResWithCert.CertInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResWithCertFormat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResWithCertFormat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CertInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CertInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ResWithCert.proto\"0\n\021ResWithCertFormat" +
      "\022\033\n\010certInfo\030\001 \003(\0132\t.CertInfo\"2\n\010CertInf" +
      "o\022\020\n\010certFile\030\001 \002(\014\022\024\n\014certFileName\030\002 \002(" +
      "\tB\rB\013ResWithCert"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ResWithCertFormat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResWithCertFormat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResWithCertFormat_descriptor,
        new java.lang.String[] { "CertInfo", });
    internal_static_CertInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CertInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CertInfo_descriptor,
        new java.lang.String[] { "CertFile", "CertFileName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
