package kr.ac.hmcl.mju.Cps_2_RA;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReqToCertInstRes.proto

public final class ReqToCertInstRes {
  private ReqToCertInstRes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqToCertInstResFormatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqToCertInstResFormat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes oemProvisioningCert = 1;</code>
     */
    boolean hasOemProvisioningCert();
    /**
     * <code>required bytes oemProvisioningCert = 1;</code>
     */
    com.google.protobuf.ByteString getOemProvisioningCert();
  }
  /**
   * Protobuf type {@code ReqToCertInstResFormat}
   */
  public  static final class ReqToCertInstResFormat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReqToCertInstResFormat)
      ReqToCertInstResFormatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqToCertInstResFormat.newBuilder() to construct.
    private ReqToCertInstResFormat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqToCertInstResFormat() {
      oemProvisioningCert_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqToCertInstResFormat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              oemProvisioningCert_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ReqToCertInstRes.internal_static_ReqToCertInstResFormat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ReqToCertInstRes.internal_static_ReqToCertInstResFormat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReqToCertInstRes.ReqToCertInstResFormat.class, ReqToCertInstRes.ReqToCertInstResFormat.Builder.class);
    }

    private int bitField0_;
    public static final int OEMPROVISIONINGCERT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString oemProvisioningCert_;
    /**
     * <code>required bytes oemProvisioningCert = 1;</code>
     */
    public boolean hasOemProvisioningCert() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes oemProvisioningCert = 1;</code>
     */
    public com.google.protobuf.ByteString getOemProvisioningCert() {
      return oemProvisioningCert_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOemProvisioningCert()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, oemProvisioningCert_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, oemProvisioningCert_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ReqToCertInstRes.ReqToCertInstResFormat)) {
        return super.equals(obj);
      }
      ReqToCertInstRes.ReqToCertInstResFormat other = (ReqToCertInstRes.ReqToCertInstResFormat) obj;

      boolean result = true;
      result = result && (hasOemProvisioningCert() == other.hasOemProvisioningCert());
      if (hasOemProvisioningCert()) {
        result = result && getOemProvisioningCert()
            .equals(other.getOemProvisioningCert());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOemProvisioningCert()) {
        hash = (37 * hash) + OEMPROVISIONINGCERT_FIELD_NUMBER;
        hash = (53 * hash) + getOemProvisioningCert().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ReqToCertInstRes.ReqToCertInstResFormat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReqToCertInstRes.ReqToCertInstResFormat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReqToCertInstRes.ReqToCertInstResFormat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReqToCertInstRes.ReqToCertInstResFormat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReqToCertInstRes.ReqToCertInstResFormat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReqToCertInstRes.ReqToCertInstResFormat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReqToCertInstRes.ReqToCertInstResFormat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReqToCertInstRes.ReqToCertInstResFormat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReqToCertInstRes.ReqToCertInstResFormat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ReqToCertInstRes.ReqToCertInstResFormat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReqToCertInstRes.ReqToCertInstResFormat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReqToCertInstRes.ReqToCertInstResFormat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ReqToCertInstRes.ReqToCertInstResFormat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReqToCertInstResFormat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqToCertInstResFormat)
        ReqToCertInstRes.ReqToCertInstResFormatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReqToCertInstRes.internal_static_ReqToCertInstResFormat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReqToCertInstRes.internal_static_ReqToCertInstResFormat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReqToCertInstRes.ReqToCertInstResFormat.class, ReqToCertInstRes.ReqToCertInstResFormat.Builder.class);
      }

      // Construct using ReqToCertInstRes.ReqToCertInstResFormat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        oemProvisioningCert_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ReqToCertInstRes.internal_static_ReqToCertInstResFormat_descriptor;
      }

      public ReqToCertInstRes.ReqToCertInstResFormat getDefaultInstanceForType() {
        return ReqToCertInstRes.ReqToCertInstResFormat.getDefaultInstance();
      }

      public ReqToCertInstRes.ReqToCertInstResFormat build() {
        ReqToCertInstRes.ReqToCertInstResFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ReqToCertInstRes.ReqToCertInstResFormat buildPartial() {
        ReqToCertInstRes.ReqToCertInstResFormat result = new ReqToCertInstRes.ReqToCertInstResFormat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.oemProvisioningCert_ = oemProvisioningCert_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReqToCertInstRes.ReqToCertInstResFormat) {
          return mergeFrom((ReqToCertInstRes.ReqToCertInstResFormat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReqToCertInstRes.ReqToCertInstResFormat other) {
        if (other == ReqToCertInstRes.ReqToCertInstResFormat.getDefaultInstance()) return this;
        if (other.hasOemProvisioningCert()) {
          setOemProvisioningCert(other.getOemProvisioningCert());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOemProvisioningCert()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReqToCertInstRes.ReqToCertInstResFormat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReqToCertInstRes.ReqToCertInstResFormat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString oemProvisioningCert_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes oemProvisioningCert = 1;</code>
       */
      public boolean hasOemProvisioningCert() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes oemProvisioningCert = 1;</code>
       */
      public com.google.protobuf.ByteString getOemProvisioningCert() {
        return oemProvisioningCert_;
      }
      /**
       * <code>required bytes oemProvisioningCert = 1;</code>
       */
      public Builder setOemProvisioningCert(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        oemProvisioningCert_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes oemProvisioningCert = 1;</code>
       */
      public Builder clearOemProvisioningCert() {
        bitField0_ = (bitField0_ & ~0x00000001);
        oemProvisioningCert_ = getDefaultInstance().getOemProvisioningCert();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReqToCertInstResFormat)
    }

    // @@protoc_insertion_point(class_scope:ReqToCertInstResFormat)
    private static final ReqToCertInstRes.ReqToCertInstResFormat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReqToCertInstRes.ReqToCertInstResFormat();
    }

    public static ReqToCertInstRes.ReqToCertInstResFormat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ReqToCertInstResFormat>
        PARSER = new com.google.protobuf.AbstractParser<ReqToCertInstResFormat>() {
      public ReqToCertInstResFormat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqToCertInstResFormat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqToCertInstResFormat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqToCertInstResFormat> getParserForType() {
      return PARSER;
    }

    public ReqToCertInstRes.ReqToCertInstResFormat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqToCertInstResFormat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReqToCertInstResFormat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ReqToCertInstRes.proto\"5\n\026ReqToCertIns" +
      "tResFormat\022\033\n\023oemProvisioningCert\030\001 \002(\014B" +
      "\022B\020ReqToCertInstRes"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ReqToCertInstResFormat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReqToCertInstResFormat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReqToCertInstResFormat_descriptor,
        new java.lang.String[] { "OemProvisioningCert", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
