package moRA;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContractData.proto

public final class ContractData {
  private ContractData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContractDataFormatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ContractDataFormat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string emaid = 1;</code>
     */
    boolean hasEmaid();
    /**
     * <code>required string emaid = 1;</code>
     */
    java.lang.String getEmaid();
    /**
     * <code>required string emaid = 1;</code>
     */
    com.google.protobuf.ByteString
        getEmaidBytes();

    /**
     * <code>required bytes dHPublicKey = 2;</code>
     */
    boolean hasDHPublicKey();
    /**
     * <code>required bytes dHPublicKey = 2;</code>
     */
    com.google.protobuf.ByteString getDHPublicKey();

    /**
     * <code>required bytes contractEncryptedPrivateKey = 3;</code>
     */
    boolean hasContractEncryptedPrivateKey();
    /**
     * <code>required bytes contractEncryptedPrivateKey = 3;</code>
     */
    com.google.protobuf.ByteString getContractEncryptedPrivateKey();

    /**
     * <code>repeated bytes contractCertChain = 4;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getContractCertChainList();
    /**
     * <code>repeated bytes contractCertChain = 4;</code>
     */
    int getContractCertChainCount();
    /**
     * <code>repeated bytes contractCertChain = 4;</code>
     */
    com.google.protobuf.ByteString getContractCertChain(int index);

    /**
     * <code>optional string pcid = 5;</code>
     */
    boolean hasPcid();
    /**
     * <code>optional string pcid = 5;</code>
     */
    java.lang.String getPcid();
    /**
     * <code>optional string pcid = 5;</code>
     */
    com.google.protobuf.ByteString
        getPcidBytes();
  }
  /**
   * Protobuf type {@code ContractDataFormat}
   */
  public  static final class ContractDataFormat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ContractDataFormat)
      ContractDataFormatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContractDataFormat.newBuilder() to construct.
    private ContractDataFormat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContractDataFormat() {
      emaid_ = "";
      dHPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      contractEncryptedPrivateKey_ = com.google.protobuf.ByteString.EMPTY;
      contractCertChain_ = java.util.Collections.emptyList();
      pcid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContractDataFormat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              emaid_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              dHPublicKey_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              contractEncryptedPrivateKey_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                contractCertChain_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000008;
              }
              contractCertChain_.add(input.readBytes());
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              pcid_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          contractCertChain_ = java.util.Collections.unmodifiableList(contractCertChain_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ContractData.internal_static_ContractDataFormat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ContractData.internal_static_ContractDataFormat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ContractData.ContractDataFormat.class, ContractData.ContractDataFormat.Builder.class);
    }

    private int bitField0_;
    public static final int EMAID_FIELD_NUMBER = 1;
    private volatile java.lang.Object emaid_;
    /**
     * <code>required string emaid = 1;</code>
     */
    public boolean hasEmaid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string emaid = 1;</code>
     */
    public java.lang.String getEmaid() {
      java.lang.Object ref = emaid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          emaid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string emaid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmaidBytes() {
      java.lang.Object ref = emaid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emaid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DHPUBLICKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString dHPublicKey_;
    /**
     * <code>required bytes dHPublicKey = 2;</code>
     */
    public boolean hasDHPublicKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes dHPublicKey = 2;</code>
     */
    public com.google.protobuf.ByteString getDHPublicKey() {
      return dHPublicKey_;
    }

    public static final int CONTRACTENCRYPTEDPRIVATEKEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString contractEncryptedPrivateKey_;
    /**
     * <code>required bytes contractEncryptedPrivateKey = 3;</code>
     */
    public boolean hasContractEncryptedPrivateKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes contractEncryptedPrivateKey = 3;</code>
     */
    public com.google.protobuf.ByteString getContractEncryptedPrivateKey() {
      return contractEncryptedPrivateKey_;
    }

    public static final int CONTRACTCERTCHAIN_FIELD_NUMBER = 4;
    private java.util.List<com.google.protobuf.ByteString> contractCertChain_;
    /**
     * <code>repeated bytes contractCertChain = 4;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getContractCertChainList() {
      return contractCertChain_;
    }
    /**
     * <code>repeated bytes contractCertChain = 4;</code>
     */
    public int getContractCertChainCount() {
      return contractCertChain_.size();
    }
    /**
     * <code>repeated bytes contractCertChain = 4;</code>
     */
    public com.google.protobuf.ByteString getContractCertChain(int index) {
      return contractCertChain_.get(index);
    }

    public static final int PCID_FIELD_NUMBER = 5;
    private volatile java.lang.Object pcid_;
    /**
     * <code>optional string pcid = 5;</code>
     */
    public boolean hasPcid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string pcid = 5;</code>
     */
    public java.lang.String getPcid() {
      java.lang.Object ref = pcid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pcid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pcid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPcidBytes() {
      java.lang.Object ref = pcid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pcid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEmaid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDHPublicKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContractEncryptedPrivateKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, emaid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, dHPublicKey_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, contractEncryptedPrivateKey_);
      }
      for (int i = 0; i < contractCertChain_.size(); i++) {
        output.writeBytes(4, contractCertChain_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, pcid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, emaid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, dHPublicKey_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, contractEncryptedPrivateKey_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < contractCertChain_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(contractCertChain_.get(i));
        }
        size += dataSize;
        size += 1 * getContractCertChainList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, pcid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ContractData.ContractDataFormat)) {
        return super.equals(obj);
      }
      ContractData.ContractDataFormat other = (ContractData.ContractDataFormat) obj;

      boolean result = true;
      result = result && (hasEmaid() == other.hasEmaid());
      if (hasEmaid()) {
        result = result && getEmaid()
            .equals(other.getEmaid());
      }
      result = result && (hasDHPublicKey() == other.hasDHPublicKey());
      if (hasDHPublicKey()) {
        result = result && getDHPublicKey()
            .equals(other.getDHPublicKey());
      }
      result = result && (hasContractEncryptedPrivateKey() == other.hasContractEncryptedPrivateKey());
      if (hasContractEncryptedPrivateKey()) {
        result = result && getContractEncryptedPrivateKey()
            .equals(other.getContractEncryptedPrivateKey());
      }
      result = result && getContractCertChainList()
          .equals(other.getContractCertChainList());
      result = result && (hasPcid() == other.hasPcid());
      if (hasPcid()) {
        result = result && getPcid()
            .equals(other.getPcid());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEmaid()) {
        hash = (37 * hash) + EMAID_FIELD_NUMBER;
        hash = (53 * hash) + getEmaid().hashCode();
      }
      if (hasDHPublicKey()) {
        hash = (37 * hash) + DHPUBLICKEY_FIELD_NUMBER;
        hash = (53 * hash) + getDHPublicKey().hashCode();
      }
      if (hasContractEncryptedPrivateKey()) {
        hash = (37 * hash) + CONTRACTENCRYPTEDPRIVATEKEY_FIELD_NUMBER;
        hash = (53 * hash) + getContractEncryptedPrivateKey().hashCode();
      }
      if (getContractCertChainCount() > 0) {
        hash = (37 * hash) + CONTRACTCERTCHAIN_FIELD_NUMBER;
        hash = (53 * hash) + getContractCertChainList().hashCode();
      }
      if (hasPcid()) {
        hash = (37 * hash) + PCID_FIELD_NUMBER;
        hash = (53 * hash) + getPcid().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ContractData.ContractDataFormat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ContractData.ContractDataFormat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ContractData.ContractDataFormat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ContractData.ContractDataFormat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ContractData.ContractDataFormat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ContractData.ContractDataFormat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ContractData.ContractDataFormat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ContractData.ContractDataFormat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ContractData.ContractDataFormat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ContractData.ContractDataFormat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ContractData.ContractDataFormat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ContractData.ContractDataFormat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ContractData.ContractDataFormat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ContractDataFormat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ContractDataFormat)
        ContractData.ContractDataFormatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ContractData.internal_static_ContractDataFormat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ContractData.internal_static_ContractDataFormat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ContractData.ContractDataFormat.class, ContractData.ContractDataFormat.Builder.class);
      }

      // Construct using ContractData.ContractDataFormat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        emaid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        dHPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        contractEncryptedPrivateKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        contractCertChain_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        pcid_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ContractData.internal_static_ContractDataFormat_descriptor;
      }

      public ContractData.ContractDataFormat getDefaultInstanceForType() {
        return ContractData.ContractDataFormat.getDefaultInstance();
      }

      public ContractData.ContractDataFormat build() {
        ContractData.ContractDataFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ContractData.ContractDataFormat buildPartial() {
        ContractData.ContractDataFormat result = new ContractData.ContractDataFormat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.emaid_ = emaid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dHPublicKey_ = dHPublicKey_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.contractEncryptedPrivateKey_ = contractEncryptedPrivateKey_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          contractCertChain_ = java.util.Collections.unmodifiableList(contractCertChain_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.contractCertChain_ = contractCertChain_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pcid_ = pcid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ContractData.ContractDataFormat) {
          return mergeFrom((ContractData.ContractDataFormat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ContractData.ContractDataFormat other) {
        if (other == ContractData.ContractDataFormat.getDefaultInstance()) return this;
        if (other.hasEmaid()) {
          bitField0_ |= 0x00000001;
          emaid_ = other.emaid_;
          onChanged();
        }
        if (other.hasDHPublicKey()) {
          setDHPublicKey(other.getDHPublicKey());
        }
        if (other.hasContractEncryptedPrivateKey()) {
          setContractEncryptedPrivateKey(other.getContractEncryptedPrivateKey());
        }
        if (!other.contractCertChain_.isEmpty()) {
          if (contractCertChain_.isEmpty()) {
            contractCertChain_ = other.contractCertChain_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureContractCertChainIsMutable();
            contractCertChain_.addAll(other.contractCertChain_);
          }
          onChanged();
        }
        if (other.hasPcid()) {
          bitField0_ |= 0x00000010;
          pcid_ = other.pcid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEmaid()) {
          return false;
        }
        if (!hasDHPublicKey()) {
          return false;
        }
        if (!hasContractEncryptedPrivateKey()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ContractData.ContractDataFormat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ContractData.ContractDataFormat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object emaid_ = "";
      /**
       * <code>required string emaid = 1;</code>
       */
      public boolean hasEmaid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string emaid = 1;</code>
       */
      public java.lang.String getEmaid() {
        java.lang.Object ref = emaid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            emaid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string emaid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmaidBytes() {
        java.lang.Object ref = emaid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emaid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string emaid = 1;</code>
       */
      public Builder setEmaid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        emaid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string emaid = 1;</code>
       */
      public Builder clearEmaid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        emaid_ = getDefaultInstance().getEmaid();
        onChanged();
        return this;
      }
      /**
       * <code>required string emaid = 1;</code>
       */
      public Builder setEmaidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        emaid_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dHPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes dHPublicKey = 2;</code>
       */
      public boolean hasDHPublicKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes dHPublicKey = 2;</code>
       */
      public com.google.protobuf.ByteString getDHPublicKey() {
        return dHPublicKey_;
      }
      /**
       * <code>required bytes dHPublicKey = 2;</code>
       */
      public Builder setDHPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dHPublicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes dHPublicKey = 2;</code>
       */
      public Builder clearDHPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dHPublicKey_ = getDefaultInstance().getDHPublicKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString contractEncryptedPrivateKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes contractEncryptedPrivateKey = 3;</code>
       */
      public boolean hasContractEncryptedPrivateKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes contractEncryptedPrivateKey = 3;</code>
       */
      public com.google.protobuf.ByteString getContractEncryptedPrivateKey() {
        return contractEncryptedPrivateKey_;
      }
      /**
       * <code>required bytes contractEncryptedPrivateKey = 3;</code>
       */
      public Builder setContractEncryptedPrivateKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        contractEncryptedPrivateKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes contractEncryptedPrivateKey = 3;</code>
       */
      public Builder clearContractEncryptedPrivateKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        contractEncryptedPrivateKey_ = getDefaultInstance().getContractEncryptedPrivateKey();
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> contractCertChain_ = java.util.Collections.emptyList();
      private void ensureContractCertChainIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          contractCertChain_ = new java.util.ArrayList<com.google.protobuf.ByteString>(contractCertChain_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated bytes contractCertChain = 4;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getContractCertChainList() {
        return java.util.Collections.unmodifiableList(contractCertChain_);
      }
      /**
       * <code>repeated bytes contractCertChain = 4;</code>
       */
      public int getContractCertChainCount() {
        return contractCertChain_.size();
      }
      /**
       * <code>repeated bytes contractCertChain = 4;</code>
       */
      public com.google.protobuf.ByteString getContractCertChain(int index) {
        return contractCertChain_.get(index);
      }
      /**
       * <code>repeated bytes contractCertChain = 4;</code>
       */
      public Builder setContractCertChain(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContractCertChainIsMutable();
        contractCertChain_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes contractCertChain = 4;</code>
       */
      public Builder addContractCertChain(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContractCertChainIsMutable();
        contractCertChain_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes contractCertChain = 4;</code>
       */
      public Builder addAllContractCertChain(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureContractCertChainIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, contractCertChain_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes contractCertChain = 4;</code>
       */
      public Builder clearContractCertChain() {
        contractCertChain_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private java.lang.Object pcid_ = "";
      /**
       * <code>optional string pcid = 5;</code>
       */
      public boolean hasPcid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string pcid = 5;</code>
       */
      public java.lang.String getPcid() {
        java.lang.Object ref = pcid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pcid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pcid = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPcidBytes() {
        java.lang.Object ref = pcid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pcid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pcid = 5;</code>
       */
      public Builder setPcid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        pcid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pcid = 5;</code>
       */
      public Builder clearPcid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        pcid_ = getDefaultInstance().getPcid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pcid = 5;</code>
       */
      public Builder setPcidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        pcid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ContractDataFormat)
    }

    // @@protoc_insertion_point(class_scope:ContractDataFormat)
    private static final ContractData.ContractDataFormat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ContractData.ContractDataFormat();
    }

    public static ContractData.ContractDataFormat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ContractDataFormat>
        PARSER = new com.google.protobuf.AbstractParser<ContractDataFormat>() {
      public ContractDataFormat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ContractDataFormat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContractDataFormat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContractDataFormat> getParserForType() {
      return PARSER;
    }

    public ContractData.ContractDataFormat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ContractDataFormat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ContractDataFormat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ContractData.proto\"\206\001\n\022ContractDataFor" +
      "mat\022\r\n\005emaid\030\001 \002(\t\022\023\n\013dHPublicKey\030\002 \002(\014\022" +
      "#\n\033contractEncryptedPrivateKey\030\003 \002(\014\022\031\n\021" +
      "contractCertChain\030\004 \003(\014\022\014\n\004pcid\030\005 \001(\tB\016B" +
      "\014ContractData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ContractDataFormat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ContractDataFormat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ContractDataFormat_descriptor,
        new java.lang.String[] { "Emaid", "DHPublicKey", "ContractEncryptedPrivateKey", "ContractCertChain", "Pcid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
